source 'http://rubygems.org'

gem 'guard'

gem 'alchemist'
gem 'eymiha_units'
gem 'geo_units'
gem 'm9t'
gem 'maventhought.units'
gem 'measurement'
gem 'quantity'
gem 'quanty'
gem 'richunits'
gem 'ruby-units'
gem 'ruby-units-brewpoo'
gem 'stick'
gem 'units'
gem 'units-system'
gem 'uom'
gem 'vanunits'
